In [30]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [31]:
df=pd.read_csv("movies_metadata.csv")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24876\2203978780.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("movies_metadata.csv")

In [32]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [33]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [34]:
df.dtypes

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [36]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [37]:
df.duplicated().sum()

np.int64(13)

In [38]:
df=df.drop_duplicates().reset_index(drop=True)

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
# sns.heatmap(df.select_dtypes(include=np.number),annot=True)

In [41]:
df_new=df[['title','overview','genres','tagline','vote_average','popularity']]

In [42]:
df_new.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [43]:
df_new['genres']

0        [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
1        [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
2        [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
3        [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
4                           [{'id': 35, 'name': 'Comedy'}]
                               ...
45448    [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...
45449                        [{'id': 18, 'name': 'Drama'}]
45450    [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...
45451                                                   []
45452                                                   []
Name: genres, Length: 45453, dtype: object

In [44]:
df_new=df_new.dropna(subset=['title'])

In [45]:
df_new.isnull().sum()

title               0
overview          954
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [46]:
df_new['overview']=df_new['overview'].fillna('')

In [47]:
df_new.isnull().sum()

title               0
overview            0
genres              0
tagline         25039
vote_average        0
popularity          0
dtype: int64

In [48]:
import ast

df_new['genres'] = df_new['genres'].apply(
    lambda x: " ".join(i['name'] for i in ast.literal_eval(x))
)

In [49]:
df_new.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [50]:
df_new['tagline']=df['tagline'].fillna('')

In [51]:
df_new.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [52]:
df_new['tags']=df_new['overview']+" "+df_new['genres']+" "+df_new['tagline']

In [53]:
df_new.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [54]:
df_new.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [55]:
df_new['tags'][0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family "

In [56]:
df_new['tags'][15]

'The life of the gambling paradise – Las Vegas – and its dark mafia underbelly. Drama Crime No one stays at the top forever.'

In [57]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [58]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...

True

In [59]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [60]:
import string
def remove_punctuation(text:str):
    text=str(text).lower()
    text=re.sub(r'[^a-zA-Z\s]','',text)
    words=text.split()
    words=[word for word in words if word not in stop_words]
    words=[lemmatizer.lemmatize(word) for word in words]
    return ' '.join(words)

df_new['tags']=df_new['tags'].apply(remove_punctuation)

In [61]:
df_new['tags'][0]

'led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference animation comedy family'

In [62]:
df_new['tags'][15]

'life gambling paradise la vega dark mafia underbelly drama crime one stay top forever'

In [63]:
df_new=df_new.reset_index(drop=True)

In [64]:
indices=pd.Series(df_new.index,index=df_new['title']).drop_duplicates()

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [66]:
tfidf=TfidfVectorizer(ngram_range=(1,2),max_features=50000,stop_words='english')

In [67]:
tfidf_matrix=tfidf.fit_transform(df_new['tags'])

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
type(indices)

pandas.core.series.Series

In [70]:
def recommend(title,n=10):
    if title not in indices:
        return ['Movie not found']
    idx=indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    print(similar_idx)
    return df_new.iloc[similar_idx]

In [71]:
recommend("Interstellar")

[36101  5459 10671  1574   312  7471 35073 45358 42682 28403]

,title,overview,genres,tagline,vote_average,popularity,tags
36101,Zero,,Drama Science Fiction,,5.3,1.000576,drama science fiction
5459,Suburban Commando,"Shep Ramsey is an interstellar hero, righting ...",Action Comedy Family Science Fiction,The Wilcoxes were having some problems around ...,4.6,4.409121,shep ramsey interstellar hero righting wrong e...
10671,Voices of a Distant Star,Voices of a Distant Star chronicles a long-dis...,Animation Science Fiction Drama,A love story that transcends time and space.,6.5,3.85131,voice distant star chronicle longdistance rela...
1574,Gattaca,Science fiction drama about a future society i...,Thriller Science Fiction Mystery Romance,There is no gene for the human spirit.,7.5,12.89312,science fiction drama future society era indef...
312,Stargate,"An interstellar teleportation device, found in...",Action Adventure Science Fiction,It will take you a million light years from ho...,6.8,13.328924,interstellar teleportation device found egypt ...
7471,Frank Herbert's Children of Dune,Under Paul ‘Muad'Dib’ Atreides' rule as Empero...,Drama Science Fiction Fantasy Adventure,Born to rule an empire. Destined to tear it ap...,6.8,3.636791,paul muaddib atreides rule emperor planet arra...
35073,The Invincible Masked Rider,,Adventure,,0.0,0.014994,adventure
45358,Simbad e il califfo di Bagdad,,Adventure,,0.0,0.006352,adventure
42682,Asteria,Two astronauts attempt to plant their flag on ...,Animation Comedy Science Fiction,"Right Planet, Wrong Time",6.7,0.549947,two astronaut attempt plant flag newly discove...
28403,France société anonyme,,Science Fiction,,4.0,0.11997,science fiction

In [85]:
recommend("Asteria")

[35154 30170 43461  9734 34814 44614 39954 44441 20471 10879]

,title,overview,genres,tagline,vote_average,popularity,tags
35154,Evil Alien Conquerors,Inept beings from the planet Kabijj land on Ea...,Comedy Science Fiction,,4.8,0.309733,inept being planet kabijj land earth attempt b...
30170,Mars,,Animation Comedy Science Fiction Romance,,5.5,0.423425,animation comedy science fiction romance
43461,Japon İşi,,Comedy Science Fiction,,6.3,0.219218,comedy science fiction
9734,The ChubbChubbs!,A janitor at an alien night-club gets his wish...,Animation Comedy Science Fiction,,6.6,1.859321,janitor alien nightclub get wish singer animat...
34814,This Isn't Funny,Meeting the right person at the wrong time can...,Comedy Drama Romance,Right Person. Wrong Time.,7.7,0.417405,meeting right person wrong time best thing eve...
44614,Duck Dodgers in the 24½th Century,Space hero Daffy battles Marvin the Martian fo...,Animation Comedy Science Fiction,,7.7,1.859834,space hero daffy battle marvin martian control...
39954,Invaders from the Deep,When aquatic aliens plot to take over the plan...,Animation Science Fiction,,0.0,0.25,aquatic alien plot take planet world aquanaut ...
44441,Spermula,"The story is based around ""spermulites"", the a...",Science Fiction Horror,,5.5,3.494968,story based around spermulites alien inhabitan...
20471,Escape from Planet Earth,Astronaut Scorch Supernova finds himself caugh...,Animation Comedy Adventure Family Science Fiction,Earth's greatest secrets are about to break out!,5.7,11.617481,astronaut scorch supernova find caught trap re...
10879,The Wild Blue Yonder,An alien narrates the story of his dying plane...,Drama Science Fiction,,5.7,0.921349,alien narrates story dying planet people visit...

In [72]:
import pickle

In [73]:
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

In [74]:
pickle.dump(indices,open('indices.pkl','wb'))

In [75]:
df_new.to_pickle('df.pkl')

In [76]:
pickle.dump(tfidf,open("tfidf.pkl",'wb'))